"""RYNTA v9.6.0 BRD Level 1 업무요건 레지스터 — tools/gen_requirements.py 생성.

손으로 고치지 않는다. 원문이 바뀌면 생성기를 다시 돌린다.
"""

SOURCE = "RYNTA_Business_Requirements_v9.6.0.html"
SOURCE_SHA256 = "e1a8daa2907c445effc1488a7d7a052d4844d2bd253f285653823be189c0dd16"

# (id, 제목, 업권, 우선순위, 수용기준 수)
REQUIREMENTS = (
    ('AIG-001', 'AI 사용사례·위험등급 등록', '공통', 'Must', 0),
    ('AIG-002', 'Read-only 기본권한', '공통', 'Must', 0),
    ('AIG-003', 'Recommend-only 판단', '공통', 'Must', 0),
    ('AIG-004', 'Approval-first 실행', '공통', 'Must', 0),
    ('AIG-005', 'Tool Registry·최소권한', '공통', 'Must', 0),
    ('AIG-006', 'DLP·마스킹', '공통', 'Must', 0),
    ('AIG-007', 'Prompt·Tool·Output 전구간 로그', '공통', 'Must', 0),
    ('AIG-008', '내부 평가셋·회귀테스트', '공통', 'Must', 0),
    ('AIG-009', 'Kill Switch·수동대체', '공통', 'Must', 0),
    ('AIG-010', 'LLM·모델 변경관리', '공통', 'Must', 0),
    ('AIG-011', '근거·한계 표시', '공통', 'Must', 0),
    ('AIG-012', 'Human-in-the-loop 최종판단', '공통', 'Must', 0),
    ('RDM-001', '유연한 원천 수집·등록', '공통', 'Must', 0),
    ('RDM-002', '집계·가공 Rule Studio', '공통', 'Must', 0),
    ('RDM-003', 'Canonical Mapping·표준화', '공통', 'Must', 0),
    ('RDM-004', 'DQ Validation·Quality Gate', '공통', 'Must', 0),
    ('RDM-005', '원천–산출–보고 Reconciliation', '공통', 'Must', 0),
    ('RDM-006', 'Field Lineage·Versioned Snapshot', '공통', 'Must', 0),
    ('RDM-007', '데이터 예외·조치 Workflow', '공통', 'Must', 0),
    ('RDM-008', '권한형 자연어 조회조건', '공통', 'Must', 0),
    ('BNK-CAP-001', 'BIS·Constraint', '은행', 'Should', 4),
    ('BNK-CAP-002', 'RAROC·거래전 의사결정', '은행', 'Should', 4),
    ('BNK-CRE-001', 'PD·LGD·EAD·CCF', '은행', 'Must', 4),
    ('BNK-CRE-002', 'SA/IRB RWA', '은행', 'Must', 4),
    ('BNK-CRE-003', '신용위험경감(CRM)·CCF·법률', '은행', 'Must', 4),
    ('BNK-CRE-004', 'Stage·SICR', '은행', 'Must', 4),
    ('BNK-CRE-005', 'ECL 측정·시나리오', '은행', 'Must', 4),
    ('BNK-CRE-006', 'PMA·IRB–ECL·GL', '은행', 'Must', 4),
    ('BNK-CRM-001', '공통 거버넌스', '은행', 'Must', 4),
    ('BNK-CRM-002', 'CSS Life Cycle', '은행', 'Must', 4),
    ('BNK-CRM-003', 'CSS 데이터·Target', '은행', 'Must', 4),
    ('BNK-CRM-004', 'CSS Scorecard', '은행', 'Must', 4),
    ('BNK-CRM-005', 'CSS 검증·전략', '은행', 'Must', 4),
    ('BNK-CRM-006', '기업 재무모형', '은행', 'Must', 4),
    ('BNK-CRM-007', '기업 비재무·대표자', '은행', 'Must', 4),
    ('BNK-CRM-008', '기업 결합·Master Scale', '은행', 'Must', 4),
    ('BNK-CRM-009', '기업 Override·EWS', '은행', 'Must', 4),
    ('BNK-OTH-001', '운영리스크', '은행', 'Should', 4),
    ('BNK-OTH-002', '시장·CCR/XVA', '은행', 'Should', 4),
    ('BNK-OTH-003', 'IRRBB·유동성', '은행', 'Should', 4),
    ('BNK-OTH-004', 'AI·기후·전략·평판', '은행', 'Should', 4),
    ('BNK-ST-001', 'Risk inventory·내부자본', '은행', 'Must', 4),
    ('BNK-ST-002', '시나리오·TD/BU', '은행', 'Must', 4),
    ('BNK-ST-003', 'Cross-risk 전이', '은행', 'Must', 4),
    ('BNK-ST-004', '손익·RWA·자본', '은행', 'Must', 4),
    ('BNK-ST-005', '한도·경영조치', '은행', 'Must', 4),
    ('BNK-ST-006', 'Reverse Stress', '은행', 'Must', 4),
    ('BNK-ST-007', '실행·Evidence', '은행', 'Must', 4),
    ('COM-001', '고객·계약 가정', '공통', 'Should', 0),
    ('COM-002', '순구축대가 산정', '공통', 'Should', 0),
    ('COM-003', 'ARR·Lifecycle·1년차·TCO 산정', '공통', 'Should', 0),
    ('COM-004', '패키지 Preset', '공통', 'Should', 0),
    ('COM-005', 'Lifecycle 요율', '공통', 'Should', 0),
    ('COM-006', '가격 승인·가정 표시', '공통', 'Should', 0),
    ('COM-007', 'ROI 이중계상 방지', '공통', 'Could', 0),
    ('COM-008', 'GTM Funnel 관리', '공통', 'Could', 0),
    ('DAT-001', 'Canonical Risk Data Model', '공통', 'Must', 0),
    ('DAT-002', '기준일·유효기간', '공통', 'Must', 0),
    ('DAT-003', 'Source-to-report Lineage', '공통', 'Must', 0),
    ('DAT-004', 'Source Registry·Snapshot', '공통', 'Must', 0),
    ('DAT-005', 'DQ 규칙', '공통', 'Must', 0),
    ('DAT-006', '수동조정 원장', '공통', 'Must', 0),
    ('DAT-007', '원천–산출–보고 대사', '공통', 'Must', 0),
    ('DAT-008', '보존·폐기·비식별', '공통', 'Must', 0),
    ('GOV-001', '데이터 원천·기준시점 통제', '공통', 'Must', 0),
    ('GOV-002', 'DQ·Lineage 통제', '공통', 'Must', 0),
    ('GOV-003', '산식·계산엔진 통제', '공통', 'Must', 0),
    ('GOV-004', '신용평가모형 통제', '공통', 'Must', 0),
    ('GOV-005', '통합 ST 통제', '공통', 'Must', 0),
    ('GOV-006', 'Market/Pricing 통제', '공통', 'Must', 0),
    ('GOV-007', 'AI/Agentic 통제', '공통', 'Must', 0),
    ('GOV-008', '변경·Lifecycle 통제', '공통', 'Must', 0),
    ('GOV-009', 'Evidence·감사 통제', '공통', 'Must', 0),
    ('INT-001', 'Read-only Secure Connector', '공통', 'Must', 0),
    ('INT-002', '파일·API·배치 연계', '공통', 'Must', 0),
    ('INT-003', '계산엔진 Adapter', '공통', 'Must', 0),
    ('INT-004', '시장데이터 Adapter', '공통', 'Must', 0),
    ('INT-005', 'IAM·SSO 연계', '공통', 'Must', 0),
    ('INT-006', 'Workflow·Ticket 연계', '공통', 'Must', 0),
    ('INT-007', '보고서 Export', '공통', 'Must', 0),
    ('INT-008', '재시도·멱등성·오류격리', '공통', 'Must', 0),
    ('NFR-001', '배포모델', '공통', 'Must', 0),
    ('NFR-002', '암호화·키관리', '공통', 'Must', 0),
    ('NFR-003', 'RBAC·직무분리', '공통', 'Must', 0),
    ('NFR-004', '감사로그 불변성', '공통', 'Must', 0),
    ('NFR-005', '성능·처리량', '공통', 'Must', 0),
    ('NFR-006', '가용성·복구', '공통', 'Must', 0),
    ('NFR-007', '확장성', '공통', 'Must', 0),
    ('NFR-008', 'Observability', '공통', 'Must', 0),
    ('NFR-009', '재현성', '공통', 'Must', 0),
    ('NFR-010', '보안검증', '공통', 'Must', 0),
    ('NFR-011', '접근성·사용성', '공통', 'Must', 0),
    ('NFR-012', '변경·배포·Rollback', '공통', 'Must', 0),
    ('PLT-001', 'Secure Connectors', '공통', 'Must', 0),
    ('PLT-002', 'Risk Data Mart', '공통', 'Must', 0),
    ('PLT-003', 'Evidence & Knowledge', '공통', 'Must', 0),
    ('PLT-004', 'Calculation & Validation', '공통', 'Must', 0),
    ('PLT-005', 'Scenario & Pricing', '공통', 'Must', 0),
    ('PLT-006', 'RAG & Agentic', '공통', 'Must', 0),
    ('PLT-007', 'Control & Observability', '공통', 'Must', 0),
    ('PLT-008', 'Reporting & Lifecycle', '공통', 'Must', 0),
    ('PLT-009', '공통 자연어 조회조건 Compiler', '공통', 'Must', 0),
    ('PLT-010', '정형 UI · Governed Schema', '공통', 'Must', 0),
    ('PLT-011', '비정형 UI · Prompt-composable Layout', '공통', 'Must', 0),
    ('PLT-012', 'UI Preview·검증·승인·Rollback', '공통', 'Must', 0),
    ('PLT-013', 'Unauthorized Field·Layout 차단', '공통', 'Must', 0),
    ('PLT-014', 'F 적합성검증 포트폴리오 · Unified Run Context', '공통', 'Must', 0),
    ('PLT-015', 'Alert-to-Action Policy Binding', '공통', 'Must', 0),
    ('PLT-016', 'Pre-execution Hold · Scoped Kill Switch', '증권', 'Must', 0),
    ('PLT-017', 'Object-based 4-Eyes · Segregation of Duties', '공통', 'Must', 0),
    ('PLT-018', 'Evidence Drill-down · Version Diff · Replay Snapshot', '공통', 'Must', 0),
    ('SEC-CCR-001', 'Netting·담보·Exposure', '증권', 'Should', 4),
    ('SEC-CCR-002', 'XVA', '증권', 'Should', 4),
    ('SEC-CCR-003', 'Margin·Collateral', '증권', 'Should', 4),
    ('SEC-LIQ-001', 'Repo·단기조달', '증권', 'Should', 4),
    ('SEC-LIQ-002', 'Liquidity Stress·CFP', '증권', 'Should', 4),
    ('SEC-MKT-001', 'VaR/ES·Stress', '증권', 'Must', 4),
    ('SEC-MKT-002', 'Sensitivities·FRTB형 분석', '증권', 'Must', 4),
    ('SEC-MKT-003', 'P&L Attribution·한도', '증권', 'Must', 4),
    ('SEC-NCR-001', '적용범위·인가', '증권', 'Must', 4),
    ('SEC-NCR-002', '영업용순자본', '증권', 'Must', 4),
    ('SEC-NCR-003', '총위험액', '증권', 'Must', 4),
    ('SEC-NCR-004', '전월·공시 대사', '증권', 'Must', 4),
    ('SEC-OAI-001', '운영손실·RCSA/KRI', '증권', 'Should', 4),
    ('SEC-OAI-002', 'AI·모델거버넌스', '증권', 'Should', 4),
    ('SEC-OAI-003', 'Agentic Close Workflow', '증권', 'Should', 4),
    ('SEC-PRC-001', '시장데이터', '증권', 'Must', 4),
    ('SEC-PRC-002', '상품명세·Pricing Model', '증권', 'Must', 4),
    ('SEC-PRC-003', '가격·Greeks 회귀', '증권', 'Must', 4),
    ('SEC-PRC-004', 'Curve·Vol·Calibration', '증권', 'Must', 4),
    ('SEC-PRC-005', 'IPV·Valuation Adjustment', '증권', 'Must', 4),
)
